credentials:
  usernames:
    vanim:
      email: victor.nyarko@ymail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Victor Nyarko     
      password: abc # Will be hashed automatically
    guser:
      email: guser@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Guest User
      password: guestuser # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - vankofy@gmail.com